title: ROS Course
email: adnan.saood@ensta-paris.fr
description: >- # this means to ignore newlines until "baseurl:"
  This is the examples homepage for the Robotics Course.
baseurl: "/notes"
url: "http://adnan-saood.github.io"
github_username:  adnan-saood

# Build settings
theme: minima
plugins:
  - jekyll-feed
