title: ROS Course
description: >- # this means to ignore newlines until "baseurl:"
  This is the examples homepage for the Robotics Course.
baseurl: "/notes"
url: "http://adnan-saood.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  # - jekyll-remote-theme
