title: ROS Course
description: >- # this means to ignore newlines until "baseurl:"
  This is the examples homepage for the Robotics Course.
baseurl: "/"
url: "http://adnan-saood.github.io"

# Build settings
remote_theme: carlosperate/jekyll-theme-rtd

repo_url: "https://github.com/adnan-saood/ros-course-examples"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
logo: 'https://asset.brandfetch.io/idDdLR3C28/idBsXi0nu5.png'