title: ROS Course Examples and Homeworks
description: This is the examples homepage for the Robotics Course.
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: ENSTA-Paris
repo_url: "https://github.com/adnan-saood/ros-course-examples"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
logo: './assets/ensta.png'


markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
