title: ROS Course Examples and Homeworks
description: This is the examples homepage for the Robotics Course.
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: ENSTA-Paris
repo_url: "https://github.com/adnan-saood/ros-course-examples"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
logo: 'https://asset.brandfetch.io/idDdLR3C28/idBsXi0nu5.png'


# Make sure to use default layout
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"
      